[package]
name = "nockapp"
version.workspace = true
edition.workspace = true

[features]
default = []

[dependencies]
nockvm = { workspace = true }
nockvm_macros = { workspace = true }

bincode = { workspace = true, features = ["serde"] }
bitvec = { workspace = true, default-features = false, features = ["alloc"] }
bytes = { workspace = true, features = ["serde"] }
either = { workspace = true }
intmap = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]

[lib]
name = "nockapp"
path = "src/lib.rs"
